Change from `on_load :active_record` to `on_load :after_initialize` to ensure the Rails configuration is available.
Otherwise one can run into this error:
  gems/railties-7.1.2/lib/rails.rb:51:in `configuration': undefined method `config' for nil:NilClass (NoMethodError)

      application.config
                 ^^^^^^^
  from gems/factory_bot_rails-6.4.0/lib/factory_bot_rails/railtie.rb:28:in `block in <class:Railtie>'