Add active_storage, action_mailer bootsnap and sass-rails gems
To address these errors:

* Address  undefined method `active_storage'

https://travis-ci.org/yahonda/factory_bot_rails/jobs/567544663#L802

```
+/home/travis/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `active_storage' for #<Rails::Application::Configuration:0x000000000417d758> (NoMethodError)
```

* Address undefined_method `action_mailer'

https://travis-ci.org/thoughtbot/factory_bot_rails/jobs/548726224#L1657

```ruby
+/home/travis/.rvm/gems/ruby-2.4.6/gems/railties-5.0.7.2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000002807418> (NoMethodError)
```

* Address `undefined method `assets'`

https://travis-ci.org/yahonda/factory_bot_rails/jobs/567544663

```
+/home/travis/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000000000337e5f8>
+Did you mean?  asset_host (NoMethodError)
```

* Address `can not load such file -- bootsnap/setup (LoadError)`

https://travis-ci.org/thoughtbot/factory_bot_rails/jobs/548726226#L1703

```ruby
+/home/travis/build/thoughtbot/factory_bot_rails/tmp/aruba/testapp/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```

Note: this commit does not address `Bundler could not find compatible versions for gem "bundler":` for Rails 4.2